# ConfigMap for non-sensitive configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: mg-test-config
  namespace: mg-test
data:
  # API Service
  PORT: "3002"
  
  # Socket Gateway Service
  GATEWAY_PORT: "3003"
  AUTH_INTROSPECT_URL: "http://api-service:3002/auth/introspect"
  AUTH_INTROSPECT_CACHE_TTL_MS: "30000"
  REDIS_URL: "redis://:$(REDIS_PASSWORD)@redis-service:6379"
  
  # Web App Service
  WEB_PORT: "3000"
  NEXT_PUBLIC_BACKEND_URL: "http://localhost:30002"
  NEXT_PUBLIC_SOKCET_GETWAY_URL: "http://localhost:30003"

