# Kustomization file for deploying all resources
# Usage: kubectl apply -k k8s/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mg-test

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - redis.yaml
  - api.yaml
  - socket.yaml
  - web.yaml

commonLabels:
  app.kubernetes.io/part-of: mg-test
  app.kubernetes.io/managed-by: kustomize

